### ISSUE TITLE
Learning to Learn Curriculum

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/software-developer#15]
### Description
Create 4 week Learning to Learn curriculum

### Problem
Cohort 3 had frustration with regards to their role as learners

#### Outcome
A delivery plan with the following objectives

#### Tasks
- [ ] Document Prep Week intro session on learning
- [x] Find and document articles shared during prep week
- [ ] Document course Intro session on learning
- [x] Find time and document sessions 1/week to talk to the cohort about learning
- [ ] Find assessments to verify learning outcomes

**Comment by dearshrewdwit** [comment]
- [ ] 1st Learning Session: https://github.com/boolean-uk/software-developer/issues/24
- [ ] 2nd learning session: 
- [ ] 3rd learning session:
- [ ] 4th learning session:
