### ISSUE TITLE
C5 Checklist

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/software-developer#81]

**Comment by dearshrewdwit** [comment]
- [ ] Set up Discord cohort category
- [ ] Set up cohort calendar
- [ ] Set up GDrive
- [ ] Confirm list of students
- [ ] Create GitHub team
- [ ] Add cohort and teachers to Montessori
- [ ] Create delivery plan and log documents
- [ ] Add day 1 - orientation plan
- [ ] Create and add work for dev env setup
- [ ] Add HTML&CSS module delivery plan
